### ISSUE TITLE
fake_useragent not found (WITH solution)

### ISSUE THREAD

**Issue by Broekinator** [MEMEZNUT999/lua#1]
When installing v2 using the install.bat file, the start.bat won't work due to the fact that the fake-useragent has not been installed (properly)

I tried running the installer again, with no results. 
Then I tried manually installing the fake-useragent myself, and it works! Now the start.bat file works as intended. 

When checking the requirements file, the fake-useragent has actually been left out. That is why it wasn't installed when running the installer.

**Comment by MEMEZNUT999** [comment]
Two things.

1 - Take a look at the repository name above. Does it spell out “Fluxus Key Bypasser” ?

2 - I actually forgot to add it lol. Thank you but please post the issue in the correct repo.
